name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: dhanya1710
          file: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: radical
          no-frame: true
          no-background: true
          max-cols: 7

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update GitHub trophies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
