name: Generate GitHub Trophies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Clone Trophy Generator
        run: git clone --depth 1 https://github.com/ryo-ma/github-profile-trophy.git trophy-generator

      - name: Generate Trophy SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          cd trophy-generator
          deno run \
            --allow-net \
            --allow-env \
            --allow-read \
            --allow-write \
            ./render_svg.ts \
            dhanya1710 \
            ../dist \
            radical

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update GitHub trophies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
