name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: dhanya1710
          output_path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
